### PR TITLE
add portainer readme file

### PR DESCRIPTION
**Pull request by Plarpoon**
As per our conversation in #33 I have created a new directory with instructions for specific edge-case scenarios setups.

At this very moment I have populated it with exclusively the Portainer setup, despite judging by the Dockge program it was linked to me before by @jammsen I might add that one soon (if required obviously).

I have also streamlined and cleaned up the .yaml that has to be used on Portainer in a way that I think it's easier to read.

### CODE REVIEW

**Comment by jammsen** [comment]
i will look tomorrow into this sorry. I need the day today for helping parents and personal stuff sorry @Plarpoon

**Comment by Plarpoon** [comment]
Oh literally zero rush, take your time! This is not a job, do things at your own pace, we are all volunteers 😊

**Comment by jammsen** [comment]
Hoi @Plarpoon - Uhhhh sorry i did take so long, but much problems got found an resolved. Looking at your document and the state the server was before a few days feels like a small eternity, so much has changed ^^

Would you be willing to join a call on Discord with me and talk about this?
Discord - jammsen
Or Teakspeak i have too.

**Comment by Plarpoon** [comment]
Sure, absolutely, sending you now a friend request so we can find each other online directly on Discord!

**Pull request closed without merging**
