### PR TITLE
[RFC] Adding portainer to README.MD and homogenizing text

### PR DESCRIPTION
**Pull request by Plarpoon**
Hello, this is the third commit based on our talk in VC yesterday @jammsen, from issues #33 and #39.

I have added the Portainer configuration as per our agreement, I have also updated it to be in sync with your newest commits and made the examples more in-line with your other previous docker-compose files.

I have also cleaned up the README.MD file as a whole as it sometimes it was using asterisk and some other times lines to determine the dot-points, which was not consistent. And I have also changed the English wording on some phrases to what I think it's easier to understand. Let me know!

### CODE REVIEW

**Comment by Plarpoon** [comment]
Let me know if some changes are needed

**Comment by jammsen** [comment]
> Let me know if some changes are needed

Hey @Plarpoon i did the final changes my self and even introduces some changes from @thejcpalma of #96 earlier 🤣 because if touched that part anyway.

**Comment by jammsen** [comment]
Thanks for the contribution! Feel free to review again if you want. I reserved the rights to sometimes go with the old text ^^

**Comment by Plarpoon** [comment]
No issues, thanks! Great job!

**Pull request merged**
