### PR TITLE
Fix UBLIC_PORT and RCON_PORT Unable to modify

### PR DESCRIPTION
**Pull request by zczm2**

### CODE REVIEW

**Comment by DiskMethod** [comment]
@zczm2 I don't think this is going to do what you're expecting. EXPOSE is mostly for documentation purposes; it won't actually publish the port or cause the server to startup on it.

You might want to look at [this](https://github.com/jammsen/docker-palworld-dedicated-server/blob/1ea15dccca206e68147e1cba1cafee90873f4557/servermanager.sh#L327) line. Also check the advanced options section on [this](https://tech.palworldgame.com/dedicated-server-guide) page.

**Comment by zczm2** [comment]
> @zczm2 I don't think this is going to do what you're expecting. EXPOSE is mostly for documentation purposes; it won't actually publish the port or cause the server to startup on it.
> 
> You might want to look at [this](https://github.com/jammsen/docker-palworld-dedicated-server/blob/1ea15dccca206e68147e1cba1cafee90873f4557/servermanager.sh#L327) line. Also check the advanced options section on [this](https://tech.palworldgame.com/dedicated-server-guide) page.

You are right, repackaging the test has no effect

But I modified line 327 of the docker palworld edited server/servermanager. sh file

Old     ./PalServer.sh "$START_OPTIONS"
New    ./PalServer.sh "$STARTOPTIONS" port="$PUBLIC-PORT"

Repackaging the test, he worked successfully!

**Comment by jammsen** [comment]
> > @zczm2 I don't think this is going to do what you're expecting. EXPOSE is mostly for documentation purposes; it won't actually publish the port or cause the server to startup on it.
> > You might want to look at [this](https://github.com/jammsen/docker-palworld-dedicated-server/blob/1ea15dccca206e68147e1cba1cafee90873f4557/servermanager.sh#L327) line. Also check the advanced options section on [this](https://tech.palworldgame.com/dedicated-server-guide) page.
> 
> You are right, repackaging the test has no effect
> 
> But I modified line 327 of the docker palworld edited server/servermanager. sh file
> 
> Old ./PalServer.sh "$START_OPTIONS" New ./PalServer.sh "$STARTOPTIONS" port="$PUBLIC-PORT"
> 
> Repackaging the test, he worked successfully!

This should not be done that way, afaik you are mixing 2 port definitions.

The people i have talked to say that the "port" defintion in the cmmand-line defines the "internal" port, while the "public_port" or "-publicport" is for the community mode, so its for EOS and game-connection is, so externally. Theese 2 have different purposes and the Docker-Best-Practice is ( taking @DiskMethod words here ) describe what this service needs to get out, to be available.

**Comment by jammsen** [comment]
> You are right, repackaging the test has no effect
> 
> But I modified line 327 of the docker palworld edited server/servermanager. sh file
> 
> Old ./PalServer.sh "$START_OPTIONS" New ./PalServer.sh "$STARTOPTIONS" port="$PUBLIC-PORT"
> 
> Repackaging the test, he worked successfully!

Also what test do you refer to?

**Pull request closed without merging**
