### PR TITLE
Enable/Disable RCON console via env variable

### PR DESCRIPTION
**Pull request by Lexiv**

### CODE REVIEW

**Comment by jammsen** [comment]
Sorry @Lexiv i have already implemented a solution to this with 3 other fixes and testing them right now.

**Comment by jammsen** [comment]
Hey @Lexiv 
Your pull-request should be already included in this https://github.com/jammsen/docker-palworld-dedicated-server/commit/ee23b8807b280d2787af71ab18cfb7a0cc51b577

Feel free to review it and decide if you miss something and let me please know

**Comment by jammsen** [comment]
@Lexiv ?

**Comment by Lexiv** [comment]
Sorry! I must have missed that somehow.
Looks good. 

I think you don’t need to be able to edit the games RCON port since this can be mapped to other port in the outside.

**Comment by jammsen** [comment]
> Sorry! I must have missed that somehow. Looks good.

No problem 👍 

> I think you don’t need to be able to edit the games RCON port since this can be mapped to any port on the outside.

Ohhh ... hmmm ... you bring up a good point ... we dont give the ability to set the PalServer.sh "port=1234" either ... changing this would be consistent with the other change right? @Lexiv

**Comment by Lexiv** [comment]
> > Sorry! I must have missed that somehow. Looks good.
> 
> No problem 👍
> 
> > I think you don’t need to be able to edit the games RCON port since this can be mapped to any port on the outside.
> 
> Ohhh ... hmmm ... you bring up a good point ... we dont give the ability to set the PalServer.sh "port=1234" either ... changing this would be consistent with the other change right? @Lexiv

Yeah because that wouldn’t really make sense either since it can be mapped to any port on the host

**Comment by jammsen** [comment]
Yeah and the Dockerfile defintion is hardcoded anyway. Thanks for your input! Do you want to close this PR? Im gonna fix the rest directly.

**Pull request closed without merging**
