### PR TITLE
change port

### PR DESCRIPTION
**Pull request by zczm2**
Fix cannot change port

### CODE REVIEW

**Comment by jammsen** [comment]
Hey @zczm2 you can change ports. This is the mapping of the internal port. Why would you want to change that?

Please explain a code change more then like 5 works 🤣

**Comment by zczm2** [comment]
Because I wanted to manage the server through k8s, but found that modifying the port was not effective because a dead port was written in the Docker file

**Comment by Plarpoon** [comment]
There are no dead ports as far as I can see.

This repo has collections of docker-compose files, would you mind sharing a link to a public repo where we can see what you are trying to do so we can have a better understanding?

Are your trying to convert this project to a kubernetes one?

**Comment by zczm2** [comment]
> 据我所知，没有死港。
> 
> 该存储库包含 docker-compose 文件的集合，您介意分享一个公共存储库的链接吗？我们可以在其中看到您正在尝试执行的操作，以便我们可以更好地理解？
> 
> 您是否正在尝试将此项目转换为 kubernetes 项目？

#90 
This RP explains my operation
Perhaps at some point, I will share it my k8s palworld server projecet

**Comment by jammsen** [comment]
That PR is as non-descriptive with no context at all as this one here is ... Cant you just take 1 minute of time please and explain what the context is?

**Pull request closed without merging**
