### PR TITLE
Add MacOS Apple silicon support

### PR DESCRIPTION
**Pull request by Ruka-2019**
## Description
Update readme and shell script to support running on MacOS M2 chips (probably M1 included)
Tested on my Mac studio with M2 Ultra.

### CODE REVIEW

**Comment by Ruka-2019** [comment]
> Hey @Ruka-2019 have you seen #6 already?
> 
> @RhanCandia @DDxPlague @nitrog0d @BrunoDomenesDutra - Have you seen this?

No I haven't seen #6 yet. Let me take a look on it.

**Comment by nitrog0d** [comment]
I thought M1 and M2 were arm based?

**Comment by Ruka-2019** [comment]
> I thought M1 and M2 were arm based?

Yes, but the `platform: linux/amd64` in the compose.yaml and the `+@sSteamCmdForcePlatformBitness 64` in the script make it somehow able to run on my m2 ultra. Although ther is still some error from the log but at least I can run and access the server from my client PC.
image

**Comment by jammsen** [comment]
> > I thought M1 and M2 were arm based?
> 
> Yes, but the `platform: linux/amd64` in the compose.yaml and the `+@sSteamCmdForcePlatformBitness 64` in the script make it somehow able to run on my m2 ultra. Although there is still some error from the log but at least I can run and access the server from my client PC. (With the code before merging upstream, commit [53064d2](https://github.com/jammsen/docker-palworld-dedicated-server/commit/53064d20e83c1f429cee54ef3e2545f98178b7d5)) image

Maybe (BIG MAYBE) the Docker-Desktop does some translation-layering? Not looked into this, no facts here, just an idea! Had no time to research this. Still working on #40

**Comment by CosminPerRam** [comment]
Specifying `platform: linux/amd64` emulates said image in docker if the host is on arm (or others), if the host is on the same architecture, it just ignores the option. This should be safe to add, as this image is already linux x64, so it shouldn't affect anything (don't quote me for the 100% corectness).

> (probably M1 included)

This isn't dependent on a specific chip, so it'll work on all apple silicon models.

**Comment by jammsen** [comment]
> Specifying `platform: linux/amd64` emulates said image in docker if the host is on arm (or others), if the host is on the same architecture, it just ignores the option. This should be safe to add, as this image is already linux x64, so it shouldn't affect anything (don't quote me for the 100% corectness).
> 
> > (probably M1 included)
> 
> This isn't dependent on a specific chip, so it'll work on all apple silicon models.

Does this include general arm64 architecture support on other devices too?

**Comment by Ruka-2019** [comment]
> Maybe (BIG MAYBE) the Docker-Desktop does some translation-layering? Not looked into this, no facts here, just an idea! Had no time to research this. Still working on https://github.com/jammsen/docker-palworld-dedicated-server/pull/40

Yes, I believe the `platform: linux/amd64` args did the job. And also the same answer I got from GPT4 which told me to try in this approach.

> Does this include general arm64 architecture support on other devices too? Because the base-image of steamcmd is only amd64 - https://hub.docker.com/layers/cm2network/steamcmd/root/images/sha256-982ef60172c654e3db3313817b1bbfaf15544c54db08705e533746f0ccd2eb1e?context=explore

I'm not sure on this, but I'm able to run the image steamcmd:root on my mac stutio. (both with and without --platform linux/amd64)
image

**Comment by jammsen** [comment]
@RhanCandia @DDxPlague @nitrog0d @BrunoDomenesDutra - Could you guys please try this? I dont any arm64 hardware, except for raspis which serve purpose and cant be used for this.

**Comment by DDxPlague** [comment]
If you're pulling [this container](https://hub.docker.com/layers/cm2network/steamcmd/root/images/sha256-982ef60172c654e3db3313817b1bbfaf15544c54db08705e533746f0ccd2eb1e?context=explore), then it's likely Rosetta is actually doing the translation/emulation of the x86 instruction set. You're also pulling an x86 base image.

This doesn't actually add support for MacOS/Apple Silicon, it just happens to run because Apple did a great job with Rosetta. I wouldn't bank on this though because Apple will eventually stop supporting Rosetta (they did it before in the PowerPC to Intel days)

**Comment by jammsen** [comment]
> If you're pulling [this container](https://hub.docker.com/layers/cm2network/steamcmd/root/images/sha256-982ef60172c654e3db3313817b1bbfaf15544c54db08705e533746f0ccd2eb1e?context=explore), then it's likely Rosetta is actually doing the translation/emulation of the x86 instruction set. You're also pulling an x86 base image.
> 
> This doesn't actually add support for MacOS/Apple Silicon, it just happens to run because Apple did a great job with Rosetta. I wouldn't bank on this though because Apple will eventually stop supporting Rosetta (they did it before in the PowerPC to Intel days).
> 
> For this to truly support Apple Silicon natively (which should be the goal IMO) we'll need to get steamcmd running on an arm64 base image (or even better get Steam to support it on arm64 natively).

Well Admins and Users are crying for years to get 64 bit and arm/arm64 support on steamcmd. I wouldnt hold my breath. The real native arm64 thing is already in the works from @nitrog0d - But for M2 silicon we could add an entry for the FAQ i guess?

**Comment by jammsen** [comment]
> But for M2 silicon we could add an entry for the FAQ i guess?

Any opinions on this anyone?

**Comment by CosminPerRam** [comment]
> Any opinions on this anyone?

This isn't specifically a fix to run on apple silicon, but to run on other than x86 hosts.
Would be great to mention that support for arm exists by enforcing x86 emulation if the host isn't that.

**Comment by jammsen** [comment]
Hey guys, im not gonna add this to the default settings to docker-compose.
If you really like to have native arm64 support please use the image of @nitrog0d here: https://github.com/nitrog0d/palworld-arm64

But i will add a FAQ entry for adding `platform: linux/amd64` to the docker-compose for non-native linux64 platforms.

**Comment by jammsen** [comment]
Added the note to the FAQ here #114

Closing this PR, thanks for the contribution and the hard work.

**Pull request closed without merging**
